[package]
name = "apples-utils"
version = "0.1.2"
edition = "2024"

[dependencies]
apples-core = {path = "../core"}
toml = "0.8"
anyhow = "1.0"
tokio= {version ="1.0", features = ["fs","io-util"]}
serde.workspace = true
clap = { version = "4.0", features = ["derive"] }
