[package]
name = "actor-macros"
version = "0.1.0"
edition = "2024"
description = "Small DSL wrapper for Ractor actors to reduce boilerplate"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.106"
quote = "1.0.40"
proc-macro2 = "1.0.101"
darling = "0.21.3"


